// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

const encode = encodeURIComponent;

const dbUrl =
  `mysql://${env("DATABASE_USER")}:` +
  `${encode(env("DATABASE_PASSWORD"))}@` +
  `${env("DATABASE_HOST")}:` +
  `${env("DATABASE_PORT")}/` +
  `${env("DATABASE_NAME")}`;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: dbUrl,
  },
});
